Update unnecessary/unsupported step statuses
adobe/aem-cloud-migration pull request #15
Opened 2021-06-16 06:19 UTC by dichaudhary

## Description

SwitchEngineHandlingProcess is added in unnecessary mapping since it is already available OOTB in AEMaaCS

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-16 20:33 UTC, ireasor requested changes
The workflow steps that are listed under UNNECESSARY are ones that are not needed on Skyline.  In theory, they wouldn't cause issues if you were to run them, but they are being handled elsewhere.  In this case, though, a customer cannot run this process in a Skyline environment as we do not allow for the execution of command line processes via a workflow.  For that reason, I think it would be better to log it under UNSUPPORTED.  

If desired, you could implement a ProfileMapper for this workflow step that reads in the customer's configuration and generates a processing profile.  If you were to do that, you could instead log this workflow step as NUI_MIGRATED.

2021-06-17 05:31 UTC, dichaudhary commented
> The workflow steps that are listed under UNNECESSARY are ones that are not needed on Skyline. In theory, they wouldn't cause issues if you were to run them, but they are being handled elsewhere. In this case, though, a customer cannot run this process in a Skyline environment as we do not allow for the execution of command line processes via a workflow. For that reason, I think it would be better to log it under UNSUPPORTED.
> 
> If desired, you could implement a ProfileMapper for this workflow step that reads in the customer's configuration and generates a processing profile. If you were to do that, you could instead log this workflow step as NUI_MIGRATED.

@ireasor, thanks for reviewing, for now, I have kept it under UNSUPPORTED to keep it consistent with other addons, ex: CameraRawHandlingProcess, PdfRasterizerHandlingProcess, etc. Once I have enough data on the common use cases of what profiles to generate, we can do it along with the other two processes also listed. let me know your thoughts!

2021-06-17 18:09 UTC, ireasor approved these changes

2021-06-17 18:14 UTC, ireasor commented
Thanks @dichaudhary.  You can find a short description of the intention for each of the types, as well as the action that we will take on them, in https://github.com/adobe/aem-cloud-migration/blob/master/src/main/java/com/adobe/skyline/migration/model/WorkflowStepSupportStatus.java.

2021-06-21 08:39 UTC, merged